export { CenteredContact } from "./templates/centered-contact"
export { MinimalLeftContact } from "./templates/minimal-left"
export { MinimalRightContact } from "./templates/minimal-right"
export { LeftAlignedContact } from "./templates/left-aligned"
export { RightAlignedContact } from "./templates/right-aligned" 